In [40]:
#YT Vid-1 By codebasics

In [41]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])

a.ndim #it provide the dimension of the array
a.itemsize # it gives how much memory takes by each element.

a.dtype # it provides data types of each element. by difult it is int32 by it can be change by defining data type when the array is created.



dtype('int32')

Array size

In [42]:
a.size # it pprovides total elements number

a.shape # it provides the shape of the array in this case the shape is 3x2

(3, 2)

Creating array with only 0 or 1 or a 1D array with a range and step


In [43]:
np.zeros((3,3)) # it will create a 3x3 array with all element value zero like np.zeros((shape))

np.ones((3,3)) # it will create a 3x3 array with all element value one like np.ones((shape))

np.arange(10) #it will create a 1D array in the range of 1 to 9 like np.arange(strat,end, step) if start value is not provided it automatically start from 0
              # is start value is not defined we can not use step size

np.linspace(1,10,10) #it will create and 1D array from strat value to end value and here 20 is the how much number I want in the range and all the numbers are linearly spaced.

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### Changing the shape of the array.

it will not affact the original array. it will provide a new array from the given array with the new shape

In [44]:
a.reshape(2,3) # it make the array 'a' from the dimension 3x2 to 2x3

np.ravel(a) # it will make the array into 1D array whatever the shape is

array([1, 2, 3, 4, 5, 6])

#### NumPy basic math operation

In [45]:
b= np.array([6,7,8,9,10,11])

b+1 # it will add 1 to all element

b-1 # it will substract 1 from all element

b*1 # it will multiple all element by 1

b/1 # it will divide all element by 1

b**2 # it will make square of all element.

np.sqrt(b) #it will make square root of all elements

np.sum(a) # it will provide sum of all elements in the array

np.min(a) # it gives the minimum number of the array

np.max(a) #it will give maximum number of the array

np.std(a) # it gives the standared daviasion of the array
b = b.reshape((3,2))


b=b.reshape(2,3)
a.dot(b) # it gives the vector multiplicaiton of a and b

array([[ 24,  27,  30],
       [ 54,  61,  68],
       [ 84,  95, 106]])

### array copying
normally when we assing the array to new varible like copy_a = a copy_a not become a separate array but it will follow the orginal array. any change in the a or copy_a make a change in both. So to avoide this type of things we need to use np.copy(name_of_array) command. this way both array will not connected to each other.

### array concatenation
In the same manner sometimes we need to join two array into a new array for this purpose we need to use np.concatenate((array1, array2)). important thing is that both array must be in same shape.

### array spliting
it is the opposite of concatenation. for that command is np.split(array, no._of_equally_sized_subarray) no_of_equally_sized_subarray must be less than no of total element of the main array

In [46]:
copy_a = np.copy(a)
copy_a[1] = [3,3]
copy_a # no effect on the original array 'a'



join_a_b = np.concatenate((a,b.reshape(3,2)))
join_a_b # array1 and array2 must be in same shape and must be write in the above formate

split_join_a_b = np.split(join_a_b,6)
split_join_a_b

[array([[1, 2]]),
 array([[3, 4]]),
 array([[5, 6]]),
 array([[6, 7]]),
 array([[8, 9]]),
 array([[10, 11]])]

### adding or removing elements
to add a new elements in the array we need to use the command as np.append(array, element_that_need_to_add) it will add the value at the end of the array.

but if we want to add the value at a certain position then we need to use the insert commant like np.insert(array, position/index, element) it will add the element in the desire position.


Now for removing a element from a spacific index we need to use the command as np.delete(array_name, position)

In [54]:
new_append = np.append(np.ravel(a),[1,2,3])

new_append = np.insert(new_append, 2 , [22,22])

old_joint_a_b = np.delete(new_append,(2,3,8,9,10))

old_joint_a_b

array([1, 2, 3, 4, 5, 6])

### Array slicing, stacking, indexing with boolean array

for spliting a array into n number(n < total number of element) of sub array we need to use the commant np.split(array_name, no_of_subarray). also the number of split san evenly divide the size of the array along the given axis

we can slicie an array to view a certain part of the array. for this the command is array[start:end]. note that this slicied array is still refering the main array so if we need to change or modified the slicied array then we need to make a copy using the .copy() function.

In [57]:
new_a = np.ravel(a)

np.split(new_a,3)

new_a[1:3]


array([2, 3])

### math operation 

numpy offers a verious math operation like addition, substraction, multiplication, division, sqrt etc. 

one important thing is the shape of the arrays must be same.

In [67]:
b=b.reshape(3,2)
add = np.add(a,b)

sub = np.subtract(a,b)

multi = np.multiply(a,b)

div = np.divide(a,b)

mod = np.mod(a,b)

power = np.power(b,a)

sqrt = np.sqrt(power)

sqrt

array([[   2.44948974,    7.        ],
       [  22.627417  ,   81.        ],
       [ 316.22776602, 1331.        ]])

### Broadcasting

It helps to perform the element wise operation also providing the advantage of shape issue for normal  operation

In [70]:
a +b #it makes a elemnt wise addition of a and b
a-b # it makes a element wise substraction of a and b
a*b #it makes a element wise multiplication of a and b
a/b # it makes a element wise division of a and b


array([[0.16666667, 0.28571429],
       [0.375     , 0.44444444],
       [0.5       , 0.54545455]])

### trigonomatric operation

using NumPy we can perfomr trigonomatric operation also but notice that it takes only radian value not degree value

In [77]:
# declearing the varibles 
x=30 # in degree value
x=x*np.pi/180 # we need to make the degree value to radian


np.sin(x) 

np.cos(x)

print(np.arcsin(x)) #to use the hyperbolic sine we  use the arc at the start like sinh(x) will be arcsin(x)

#in same way we can perfomr tan, cot, sec, cosec etc

0.5510695830994463


### exponentials and logarithms

to perform exponential operation and logarithmic operation there are scoops. 

--> for exponential np.exp(value)

--> for e base log np.log(value)

--> for 10 base log np.log10(value)

--> for 2base log np.log2(value)

In [81]:
exp = np.exp(x)
exp

ln = np.log(x)
ln

log10 = np.log10(x)
log10

log2 = np.log2(x)
log2

-0.9334663712488376

### statistical functions

In [88]:
std= np.std(a)  # it makes standerd diviation of the all array elements
std

var = np.var(a) #it makes the variance of the all array elements
var

Co_Relation_coeeficient =np.corrcoef(np.ravel(a))
Co_Relation_coeeficient

1.0

### searching and sorting

In [99]:
min_element_index = np.argmin(a) # it gives the minimum value elemnts index
min_element_index

max_element_index = np.argmax(a) # it gives the maximum value element index
max_element_index


cond_a = np.ravel(a)
cond = np.where(cond_a%2==0)  # it gives the index of the array element position where the given condition is satisfied
cond

sort_assen= np.sort(a) #it sort the array in assending order
sort_assen

sort_disen = np.sort(a)[::-1] #it sort the array elements in disending order
sort_disen

sorting_index = np.argsort(sort_disen) #it gives the index number for which the array will sort in assending maner
sorting_index

array([[0, 1],
       [0, 1],
       [0, 1]], dtype=int64)

### linear algebra
like matirx operation

In [105]:
b=b.reshape(2,3)
dot_product = np.dot(a,b)
dot_product

inverrse_matrix = np.linalg.inv(dot_product)
inverrse_matrix

eigen_value_ofthe_matrix = np.linalg.eig(dot_product)
eigen_value_ofthe_matrix

EigResult(eigenvalues=array([ 1.90811332e+02,  1.88668040e-01, -1.01189018e-14]), eigenvectors=array([[-0.23225104, -0.7579317 ,  0.40824829],
       [-0.52539813, -0.0539148 , -0.81649658],
       [-0.81854521,  0.6501021 ,  0.40824829]]))

### saving array and loading array
to save a array we use np.save((need to add the direction if needed)filename.npy,array) and to load the array we need to use np.load('name_array_file.npy')