In [40]:
#YT Vid-1 By codebasics

In [41]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])

a.ndim #it provide the dimension of the array
a.itemsize # it gives how much memory takes by each element.

a.dtype # it provides data types of each element. by difult it is int32 by it can be change by defining data type when the array is created.



dtype('int32')

Array size

In [42]:
a.size # it pprovides total elements number

a.shape # it provides the shape of the array in this case the shape is 3x2

(3, 2)

Creating array with only 0 or 1 or a 1D array with a range and step


In [43]:
np.zeros((3,3)) # it will create a 3x3 array with all element value zero like np.zeros((shape))

np.ones((3,3)) # it will create a 3x3 array with all element value one like np.ones((shape))

np.arange(10) #it will create a 1D array in the range of 1 to 9 like np.arange(strat,end, step) if start value is not provided it automatically start from 0
              # is start value is not defined we can not use step size

np.linspace(1,10,10) #it will create and 1D array from strat value to end value and here 20 is the how much number I want in the range and all the numbers are linearly spaced.

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### Changing the shape of the array.

it will not affact the original array. it will provide a new array from the given array with the new shape

In [44]:
a.reshape(2,3) # it make the array 'a' from the dimension 3x2 to 2x3

np.ravel(a) # it will make the array into 1D array whatever the shape is

array([1, 2, 3, 4, 5, 6])

#### NumPy basic math operation

In [45]:
b= np.array([6,7,8,9,10,11])

b+1 # it will add 1 to all element

b-1 # it will substract 1 from all element

b*1 # it will multiple all element by 1

b/1 # it will divide all element by 1

b**2 # it will make square of all element.

np.sqrt(b) #it will make square root of all elements

np.sum(a) # it will provide sum of all elements in the array

np.min(a) # it gives the minimum number of the array

np.max(a) #it will give maximum number of the array

np.std(a) # it gives the standared daviasion of the array
b = b.reshape((3,2))

a +b #it makes a elemnt wise addition of a and b
a-b # it makes a element wise substraction of a and b
a*b #it makes a element wise multiplication of a and b
a/b # it makes a element wise division of a and b

b=b.reshape(2,3)
a.dot(b) # it gives the vector multiplicaiton of a and b

array([[ 24,  27,  30],
       [ 54,  61,  68],
       [ 84,  95, 106]])

### array copying
normally when we assing the array to new varible like copy_a = a copy_a not become a separate array but it will follow the orginal array. any change in the a or copy_a make a change in both. So to avoide this type of things we need to use np.copy(name_of_array) command. this way both array will not connected to each other.

### array concatenation
In the same manner sometimes we need to join two array into a new array for this purpose we need to use np.concatenate((array1, array2)). important thing is that both array must be in same shape.

### array spliting
it is the opposite of concatenation. for that command is np.split(array, no._of_equally_sized_subarray) no_of_equally_sized_subarray must be less than no of total element of the main array

In [46]:
copy_a = np.copy(a)
copy_a[1] = [3,3]
copy_a # no effect on the original array 'a'



join_a_b = np.concatenate((a,b.reshape(3,2)))
join_a_b # array1 and array2 must be in same shape and must be write in the above formate

split_join_a_b = np.split(join_a_b,6)
split_join_a_b

[array([[1, 2]]),
 array([[3, 4]]),
 array([[5, 6]]),
 array([[6, 7]]),
 array([[8, 9]]),
 array([[10, 11]])]

### adding or removing elements
to add a new elements in the array we need to use the command as np.append(array, element_that_need_to_add) it will add the value at the end of the array.

but if we want to add the value at a certain position then we need to use the insert commant like np.insert(array, position/index, element) it will add the element in the desire position.


Now for removing a element from a spacific index we need to use the command as np.delete(array_name, position)

In [54]:
new_append = np.append(np.ravel(a),[1,2,3])

new_append = np.insert(new_append, 2 , [22,22])

old_joint_a_b = np.delete(new_append,(2,3,8,9,10))

old_joint_a_b

array([1, 2, 3, 4, 5, 6])

### Array slicing, stacking, indexing with boolean array

for spliting a array into n number(n < total number of element) of sub array we need to use the commant np.split(array_name, no_of_subarray). also the number of split san evenly divide the size of the array along the given axis

we can slicie an array to view a certain part of the array. for this the command is array[start:end]. note that this slicied array is still refering the main array so if we need to change or modified the slicied array then we need to make a copy using the .copy() function.

In [57]:
new_a = np.ravel(a)

np.split(new_a,3)

new_a[1:3]


array([2, 3])

### math operation 

numpy offers a verious math operation 